import { ASSEMBLY } from "../../constants";

export const OPCODES: Record<string, number> = {
  [ASSEMBLY.ADDITION]: 0x01,
  [ASSEMBLY.SUBTRACTION]: 0x02,
  [ASSEMBLY.MULTIPLICATION]: 0x03,
  [ASSEMBLY.DIVISION]: 0x04,
  [ASSEMBLY.REMAINDER]: 0x05,
  [ASSEMBLY.POWER]: 0x06,
  [ASSEMBLY.GREATER]: 0x07,
  [ASSEMBLY.LESS]: 0x08,
  [ASSEMBLY.GREATER_EQUAL]: 0x09,
  [ASSEMBLY.LESS_EQUAL]: 0x0a,
  [ASSEMBLY.ASSIGNMENT]: 0x0b,
  [ASSEMBLY.REFERENCE]: 0x0c,
  [ASSEMBLY.JUMP]: 0x0d,
  [ASSEMBLY.JUMP_IF_FALSE]: 0x0e,
  [ASSEMBLY.NUMBER]: 0x0f,
  [ASSEMBLY.STRING]: 0x10,
  [ASSEMBLY.OUTPUT]: 0x11,
  [ASSEMBLY.END]: 0xff,
} as const;
