import { ASSEMBLY } from "../../constants";

export const OPCODES: Record<string, number> = {
  [ASSEMBLY.ADDITION]: 0x01,
  [ASSEMBLY.SUBTRACTION]: 0x02,
  [ASSEMBLY.MULTIPLICATION]: 0x03,
  [ASSEMBLY.DIVISION]: 0x04,
  [ASSEMBLY.REMAINDER]: 0x05,
  [ASSEMBLY.POWER]: 0x06,
  [ASSEMBLY.NUMBER]: 0x07,
  [ASSEMBLY.OUTPUT]: 0x08,
  [ASSEMBLY.END]: 0xff,
} as const;
