export const ASSEMBLY = {
  // 四則演算
  ADDITION: "ADD",
  SUBTRACTION: "SUB",
  MULTIPLICATION: "MUL",
  DIVISION: "DIV",
  REMAINDER: "REM",
  POWER: "POW",

  // 変数
  ASSIGNMENT: "STORE",
  REFERENCE: "LOAD",

  OUTPUT: "PUTS",
  FUNCTION_CALL: "CALL",
  NUMBER: "PUSH",
  END: "HALT",
} as const;
